name: Health Check

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Health Check
        run: curl https://tw-etf-line-bot.azurewebsites.net
